# Generated by Django 4.1.3 on 2023-06-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_settlement_expense_remove_settlement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
