# Generated by Django 4.1.3 on 2023-06-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_expense_id_alter_group_id_alter_settlement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.expense'),
        ),
    ]
